language: python
env:
  global:
  # Set defaults to avoid repeating in most cases
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='coveralls coverage mock six numpy pandas geojson shapely cartopy pycrs pytz dask docutils pyyaml codecov pytest pytest-cov'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request cron'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY="strict"

matrix:
  include:
    - env: PYTHON_VERSION=3.8
      os: linux
    - env: PYTHON_VERSION=3.8
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.9
      os: linux
    - env: PYTHON_VERSION=3.9
      os: osx
      language: generic
install:
#    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - git clone --depth 1 -b all-the-fixes git://github.com/djhoese/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install -e .
script:
  - py.test  --cov-report term --cov=./
